---
- hosts: localhost
  vars:
    helm_chart_url: "http://charts.k8strilio.net/trilio-stable/k8s-triliovault-operator"
  tasks:
    - name: Download helm binary archive.
      get_url:
        url: https://get.helm.sh/helm-v3.2.1-linux-amd64.tar.gz
        dest: /tmp/helm-v3.2.1-linux-amd64.tar.gz
    - name: Add env varibale
      shell: export PATH=$PATH:/opt/app-root/src/bin:/opt/app-root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: Unarchive the helm repo
      shell: gunzip /tmp/helm-v3.2.1-linux-amd64.tar.gz
    - name: Adding wait
      wait_for:
        delay: 20
    - name: Install tar
      yum: name=https://vault.centos.org/centos/8/BaseOS/x86_64/os/Packages/tar-1.30-5.el8.x86_64.rpm
    - name: Untar the tar file
      shell: /usr/bin/tar -vxf /tmp/helm-v3.2.1-linux-amd64.tar
      args:
        executable: /bin/bash
    - name: Move helm binary into place.
      command: cp /tmp/linux-amd64/helm /usr/local/bin/helm
      args:
        creates: /usr/local/bin/helm
    - name: Add helm repo
      kubernetes.core.helm_repository:
        name: triliovault-operator
        repo_url: "{{ helm_chart_url }}"
    - name: Install TVK chart
      kubernetes.core.helm:
        name: triliovault-operator
        namespace: tvk
        chart_ref: triliovault-operator/k8s-triliovault-operator
