apiVersion: triliovault.trilio.io/v1
kind: License
metadata:
  name: trilio-license
  namespace: trilio-system
spec:
  secretRef:
    apiVersion: v1
    kind: Secret
    name: tvk-license-vcb
    namespace: trilio-system
