apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: k8s-triliovault
  namespace: trilio-system
spec:
  channel: 5.3.x
  installPlanApproval: Automatic
  name: k8s-triliovault
  source: certified-operators
  sourceNamespace: openshift-marketplace
