import { test, expect } from '@playwright/test';

test.use({
  ignoreHTTPSErrors: true
});

test('test', async ({ page }) => {
  await page.goto('https://trilio-system.apps.<your-cluster>/#/login');
  await page.getByRole('button', { name: 'Openshift Sign-in via' }).click();
  await page.goto('https://oauth-openshift.apps.<your-cluster>/login?then=%2Foauth%2Fauthorize%3Fclient_id%3Dsystem%253Aserviceaccount%253Atrilio-system%253Ak8s-triliovault%26redirect_uri%3Dhttps%253A%252F%252Ftrilio-system.apps.<your-cluster>%252Fdex%252Fcallback%26response_type%3Dcode%26scope%3Duser%253Ainfo%26state%3Dkpciyowurelono5j4rccxe5b2');
  await page.getByRole('textbox', { name: 'Username' }).fill('kubeadmin');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('');
  await page.getByRole('button', { name: 'Log in' }).click();
  await page.goto('https://trilio-system.apps.<your-cluster>/#/cluster-management/list');
  await page.getByRole('link', { name: 'Backup & Recovery' }).click();
  await page.getByRole('link', { name: 'Backup Plans' }).click();
  await page.getByRole('link', { name: 'helm-bp-c3a' }).click();
  await page.getByRole('button', { name: 'View Backups' }).click();
  await page.getByRole('button', { name: 'Restore' }).click();
  await page.getByRole('textbox', { name: 'Name' }).click();
  await page.getByRole('textbox', { name: 'Name' }).fill('test-rest');
  await page.getByText('Select Namespace').click();
  await page.getByText('Select Namespace').click();
  await page.getByText('Select Namespace').click();
  await page.getByText('es-hook-test', { exact: true }).click();
  await page.getByRole('button', { name: 'Create' }).click();
  await page.getByRole('button', { name: 'Cancel' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('form').click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByText('Add Transform Components').click();
  await page.locator('div').filter({ hasText: /^Custom$/ }).nth(2).click();
  await page.locator('#react-select-14-input').press('ControlOrMeta+c');
  await page.getByTestId('restore-wizard-container').getByText('Helm', { exact: true }).click();
  await page.locator('.helm-component-accordion > .d-flex > .icon-container > .c-pointer').click();
  await page.getByRole('textbox', { name: 'Transform Name' }).click();
  await page.getByRole('textbox', { name: 'Transform Name' }).fill('test-transform');
  await page.getByRole('textbox', { name: 'Transform Name' }).click();
  await page.locator('.visible.scrollbar.vertical > .slider').click();
  await page.locator('.visible.scrollbar.vertical > .slider').click();
  await page.getByRole('textbox', { name: 'Transform Name' }).press('ControlOrMeta+c');
  await page.locator('.visible.scrollbar.vertical > .slider').click();
  await page.locator('.visible.scrollbar.vertical > .slider').click();
  await page.locator('.visible.scrollbar.vertical').dblclick();
  await page.locator('.view-lines > div:nth-child(3)').click();
  await page.getByRole('textbox', { name: 'Editor content;Press Alt+F1' }).fill('  serviceMonitor:\n    additionalLabels: {}\n    enabled: false\nmysqlx:\n  port:\n    enabled: true\nnodeSelector: {}\npersistence:\n  accessMode: "ReadWriteOnce"\n  annotations: {}\n');
  await page.getByText(':', { exact: true }).nth(2).click();
  await page.locator('.view-lines > div:nth-child(3)').click();
  await page.locator('.view-lines > div:nth-child(3)').dblclick();
  await page.getByText('Transform NameEdit the below').click();
  await page.locator('.visible.scrollbar.vertical > .slider').click();
  await page.locator('.visible.scrollbar.vertical').click();
  await page.locator('.visible.scrollbar.vertical').click();
  await page.locator('.visible.scrollbar.vertical > .slider').click();
  await page.locator('.visible.scrollbar.vertical > .slider').click();
  await page.getByText('enabled').first().click();
  await page.getByRole('textbox', { name: 'Editor content;Press Alt+F1' }).press('ArrowUp');
  await page.getByRole('textbox', { name: 'Editor content;Press Alt+F1' }).press('ArrowUp');
  await page.getByRole('textbox', { name: 'Editor content;Press Alt+F1' }).press('ArrowUp');
  await page.getByRole('textbox', { name: 'Editor content;Press Alt+F1' }).press('ControlOrMeta+c');
  await page.getByRole('textbox', { name: 'Editor content;Press Alt+F1' }).press('ControlOrMeta+c');
  await page.getByRole('button', { name: 'Apply' }).click();
  await page.getByRole('button', { name: 'Add' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
});