apiVersion: v1
kind: Secret
metadata:
  name: cassandra-app-secret
type: Opaque
stringData:
  username: admin
  password: secret123
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cassandra-config
data:
  env: dev